# Generated by Django 6.1.1 on 2026-09-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Framework', 'Framework'), ('Langage', 'Langage'), ('DevOps', 'DevOps')], default='Langage', max_length=50),
        ),
    ]
