# Generated by Django 6.1.1 on 2026-09-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
